name: Deploy to AWS S3

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        node --version
        npm --version
        npm install
    
    - name: Build application
      run: npm run build
      env:
        CI: false
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Create S3 bucket if not exists
      run: |
        aws s3 mb s3://${{ secrets.S3_BUCKET_NAME }} --region ap-southeast-2 || echo "Bucket already exists"
    
    - name: Configure S3 bucket for static hosting
      run: |
        aws s3 website s3://${{ secrets.S3_BUCKET_NAME }} --index-document index.html --error-document index.html
    
    - name: Set bucket policy for public access
      run: |
        cat > bucket-policy.json << EOF
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::\${{ secrets.S3_BUCKET_NAME }}/*"
            }
          ]
        }
        EOF
        aws s3api put-bucket-policy --bucket ${{ secrets.S3_BUCKET_NAME }} --policy file://bucket-policy.json
    
    - name: Disable block public access
      run: |
        aws s3api put-public-access-block --bucket ${{ secrets.S3_BUCKET_NAME }} --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
    
    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --region ap-southeast-2
    
    - name: Show deployment URL
      run: |
        echo "🚀 Deployment complete!"
        echo "📱 Access your site at: http://${{ secrets.S3_BUCKET_NAME }}.s3-website-ap-southeast-2.amazonaws.com"